"""
内联种子代码。
"""

SEED_CODE = 'import numpy as np\nimport numpy as np\nfrom typing import Tuple\n\ndef heuristics_v2(distance_matrix: np.ndarray) -> np.ndarray:\n    """\n    Enhanced heuristic focusing on central nodes and edge uniqueness.\n    Returns penalty matrix where higher values indicate worse edges for TSP.\n    """\n    n = len(distance_matrix)\n    \n    if n <= 2:\n        return np.zeros_like(distance_matrix) if n > 0 else distance_matrix\n    \n    # 1. STRONG centrality penalty - edges connecting central nodes get high penalty\n    # Central nodes are those with small average distance to other nodes\n    avg_distances = np.sum(distance_matrix, axis=1) / (n - 1)\n    \n    # Invert so smaller average distance = higher centrality score\n    min_avg, max_avg = np.min(avg_distances), np.max(avg_distances)\n    if max_avg > min_avg:\n        centrality = 1.0 - (avg_distances - min_avg) / (max_avg - min_avg)\n    else:\n        centrality = np.ones(n)\n    \n    # Amplify centrality differences using power scaling\n    centrality = centrality ** 2\n    \n    # Create centrality penalty matrix\n    # Using outer product for efficient computation\n    centrality_matrix = np.outer(centrality, centrality)\n    \n    # 2. STRONG edge uniqueness penalty - edges with few alternatives get high penalty\n    # Sort distances to find k-nearest neighbors for each node\n    k = min(10, n - 1)\n    \n    # Get sorted indices for each row (excluding self)\n    sorted_indices = np.argsort(distance_matrix, axis=1)[:, 1:k+1]\n    \n    # Create neighbor count matrix\n    neighbor_count = np.zeros((n, n), dtype=int)\n    \n    for i in range(n):\n        # Mark k-nearest neighbors\n        neighbor_count[i, sorted_indices[i]] = 1\n    \n    # Symmetrize - an edge is "common" if it\'s in k-nearest of either endpoint\n    common_edges = np.maximum(neighbor_count, neighbor_count.T)\n    \n    # Uniqueness penalty: edges NOT in k-nearest neighbors get higher penalty\n    uniqueness_penalty = 1.0 - common_edges.astype(float)\n    \n    # 3. Edge length component (normalized)\n    max_dist = np.max(distance_matrix)\n    if max_dist > 0:\n        length_penalty = distance_matrix / max_dist\n    else:\n        length_penalty = np.zeros_like(distance_matrix)\n    \n    # 4. Combined penalty with emphasis on centrality and uniqueness\n    # Weights can be adjusted based on problem characteristics\n    penalty_matrix = (\n        0.4 * centrality_matrix +    # Strong focus on central nodes\n        0.4 * uniqueness_penalty +   # Strong focus on unique edges  \n        0.2 * length_penalty         # Moderate focus on edge length\n    )\n    \n    # Ensure symmetry\n    penalty_matrix = (penalty_matrix + penalty_matrix.T) / 2\n    \n    # Zero diagonal\n    np.fill_diagonal(penalty_matrix, 0)\n    \n    # Normalize to [0, 1] range\n    max_penalty = np.max(penalty_matrix)\n    if max_penalty > 0:\n        penalty_matrix = penalty_matrix / max_penalty\n    \n    return penalty_matrix\n'


def get_seed_code() -> str:
    """返回内联的种子源码字符串。"""
    return SEED_CODE.strip()
