"""
内联种子代码。
"""

SEED_CODE = "import numpy as np\nimport numpy as np\n\ndef heuristics_v2(prize: np.ndarray, distance: np.ndarray, maxlen: float) -> np.ndarray:\n    n = len(prize)\n    \n    # Create safe distance matrix to avoid division by zero\n    safe_dist = distance.copy()\n    safe_dist[safe_dist == 0] = 1e-8\n    \n    # 1. Core prize-to-distance ratio (normalized)\n    prize_to_dist = prize / safe_dist\n    ptd_max = prize_to_dist.max()\n    if ptd_max > 0:\n        prize_to_dist = prize_to_dist / ptd_max\n    \n    # 2. Budget feasibility factor (exponential decay)\n    dist_ratio = distance / maxlen\n    budget_factor = np.exp(-3 * dist_ratio)\n    \n    # 3. Simple prize diffusion via normalized adjacency\n    # Use inverse distance as connectivity measure\n    with np.errstate(divide='ignore'):\n        connectivity = 1.0 / safe_dist\n    np.fill_diagonal(connectivity, 0)\n    \n    # Row-normalize to get weights\n    row_sums = connectivity.sum(axis=1, keepdims=True)\n    row_sums[row_sums == 0] = 1.0\n    weights = connectivity / row_sums\n    \n    # Compute diffused prize scores\n    diffused_prize = weights @ prize\n    dp_max = diffused_prize.max()\n    if dp_max > 0:\n        diffused_prize = diffused_prize / dp_max\n    \n    # 4. Combined score with clear weighting\n    combined = (prize_to_dist * \n                budget_factor * \n                (0.5 + 0.5 * diffused_prize[:, np.newaxis]))\n    \n    # 5. Depot handling: prioritize leaving depot, encourage returning\n    combined[0, :] *= 1.3  # From depot bonus\n    combined[:, 0] *= 1.2  # To depot bonus\n    \n    # 6. Adaptive sparsification - keep more edges for depot\n    k_base = max(3, n // 10)\n    heur = np.zeros((n, n))\n    \n    for i in range(n):\n        if i == 0:\n            # Depot: keep more connections\n            k = min(n, k_base * 2)\n        else:\n            k = k_base\n        \n        # Get top-k edges\n        sorted_indices = np.argsort(combined[i])[::-1]\n        top_k_indices = sorted_indices[:k]\n        heur[i, top_k_indices] = combined[i, top_k_indices]\n    \n    # 7. Final normalization\n    h_max = heur.max()\n    if h_max > 0:\n        heur = heur / h_max\n    \n    # Zero diagonal\n    np.fill_diagonal(heur, 0)\n    \n    return heur\n"


def get_seed_code() -> str:
    """返回内联的种子源码字符串。"""
    return SEED_CODE.strip()
