"""
内联种子代码。
"""

SEED_CODE = 'import numpy as np\nimport numpy as np\n\ndef heuristics_v2(distance_matrix: np.ndarray) -> np.ndarray:\n    n = len(distance_matrix)\n    eps = 1e-10\n    dist = np.where(distance_matrix == np.inf, np.inf, distance_matrix) + eps\n\n    # Heuristic 1: Inverse distance – prioritize shorter edges\n    inv_dist = 1.0 / dist\n    inv_dist = np.where(np.isinf(inv_dist), 0, inv_dist)\n\n    # Heuristic 2: Node centrality – favor edges between low-degree nodes\n    degrees = np.sum(dist < np.inf, axis=1)\n    node_centrality = 1.0 / (degrees + eps)\n    centrality_edge_score = np.outer(node_centrality, node_centrality)\n\n    # Heuristic 3: Local diversity – prefer connecting to less connected neighbors\n    k = min(5, n)\n    sorted_neighbors = np.argsort(dist, axis=1)\n    diversity_score = np.zeros_like(dist)\n\n    for i in range(n):\n        neighbors = sorted_neighbors[i, :k]\n        proximity_weight = 1.0 / (np.arange(1, k + 1) + eps)\n        connectivity_penalty = 1.0 / (degrees[neighbors] + eps)\n        diversity_score[i, neighbors] = proximity_weight * connectivity_penalty\n\n    # Heuristic 4: Symmetry-aware preference – promote consistent bidirectional edges\n    connectivity = np.where(dist < np.inf, 1.0, 0.0)\n    symmetry_score = (connectivity + connectivity.T) / 2\n\n    # Heuristic 5: Balance – reduce hub dominance using geometric mean\n    hub_balance = np.sqrt(node_centrality[:, None] * node_centrality[None, :])\n    balance_score = 1.0 / (hub_balance + eps)\n\n    # Adaptive weighting based on graph density\n    avg_degree = np.mean(degrees)\n    density_factor = np.clip(avg_degree / n, 0.05, 0.8)\n    alpha = 1.8 * (1 - density_factor)  # Higher centrality in sparse graphs\n    beta = 1.4 * density_factor         # Higher diversity in dense graphs\n    gamma = 1.1 * (1 - 0.4 * density_factor)  # Less symmetry emphasis in dense\n    delta = 2.2 * density_factor       # More balance emphasis in dense\n\n    # Unified geometric fusion with entropy-inspired shaping\n    combined = (\n        inv_dist ** 1.35 *\n        (centrality_edge_score + eps) ** alpha *\n        (diversity_score + eps) ** beta *\n        (symmetry_score + eps) ** gamma *\n        (balance_score + eps) ** delta\n    )\n\n    # Entropy-guided sparsification with top-k edges per node\n    k = max(2, int(0.25 * n))\n    top_edges_per_node = np.argsort(combined, axis=1)[:, -k:]\n\n    # Build sparse heuristic matrix\n    result = np.zeros_like(combined)\n    for i in range(n):\n        result[i, top_edges_per_node[i]] = combined[i, top_edges_per_node[i]]\n\n    # Normalize per node to maintain relative edge quality\n    row_norms = np.sum(result, axis=1, keepdims=True)\n    result = np.where(row_norms > 0, result / (row_norms + eps), result)\n\n    # Enforce symmetry (undirected graph)\n    result = (result + result.T) / 2\n\n    # Remove self-loops\n    np.fill_diagonal(result, 0)\n\n    return result\n'


def get_seed_code() -> str:
    """返回内联的种子源码字符串。"""
    return SEED_CODE.strip()
