"""
内联种子代码。
"""

SEED_CODE = 'import numpy as np\nimport numpy as np\n\ndef crossover_v2(parents: np.ndarray, n_pop: int) -> np.ndarray:\n    """\n    Simplified yet effective crossover function for decap placement optimization.\n    Features:\n    1. Multi-point crossover with random crossover points\n    2. Uniform crossover with fixed probability\n    3. Vectorized implementation for efficiency\n    4. Random parent selection without tournament overhead\n    """\n    n_parents, n_decap = parents.shape\n    \n    # Parameters\n    uniform_crossover_prob = 0.3\n    blend_alpha = 0.4\n    \n    # Initialize offspring array\n    offspring = np.zeros((n_pop, n_decap), dtype=parents.dtype)\n    \n    # Generate all random selections upfront for vectorization\n    parent_indices = np.random.randint(0, n_parents, size=(n_pop, 2))\n    parent1_indices, parent2_indices = parent_indices[:, 0], parent_indices[:, 1]\n    \n    # Get parent pairs\n    parent1 = parents[parent1_indices]\n    parent2 = parents[parent2_indices]\n    \n    # Pre-generate random strategy choices for each offspring\n    strategies = np.random.rand(n_pop)\n    \n    # Pre-generate uniform crossover masks for all offspring\n    uniform_masks = np.random.rand(n_pop, n_decap) < uniform_crossover_prob\n    \n    for i in range(n_pop):\n        p1, p2 = parent1[i], parent2[i]\n        strategy = strategies[i]\n        \n        if strategy < 0.5:\n            # Multi-point crossover (1-3 points)\n            n_points = np.random.randint(1, min(4, n_decap))\n            points = np.sort(np.random.choice(range(1, n_decap), n_points, replace=False))\n            points = np.concatenate([[0], points, [n_decap]])\n            \n            child = np.empty(n_decap, dtype=parents.dtype)\n            use_p1 = True\n            \n            for start, end in zip(points[:-1], points[1:]):\n                if use_p1:\n                    child[start:end] = p1[start:end]\n                else:\n                    child[start:end] = p2[start:end]\n                use_p1 = not use_p1\n                \n        elif strategy < 0.8:\n            # Uniform crossover\n            mask = uniform_masks[i]\n            child = np.where(mask, p1, p2)\n            \n        else:\n            # Blend crossover\n            if np.all(np.isin(parents, [0, 1])):  # Binary case\n                blend = blend_alpha * p1 + (1 - blend_alpha) * p2\n                child = (blend > 0.5).astype(parents.dtype)\n            else:  # Continuous case\n                child = blend_alpha * p1 + (1 - blend_alpha) * p2\n        \n        offspring[i] = child\n    \n    return offspring\n'


def get_seed_code() -> str:
    """返回内联的种子源码字符串。"""
    return SEED_CODE.strip()
